name: Compilar firmware CardPuter ADV USB MSC

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install platformio
      - run: pio run
      - uses: actions/upload-artifact@v4
        with:
          name: cardputer_adv_usb_msc_mac
          path: |
            .pio/build/cardputer_adv/firmware.bin
            .pio/build/cardputer_adv/bootloader.bin
            .pio/build/cardputer_adv/partitions.bin
          retention-days: 90
